{
 "title": "Medistream Backend Metrics",
 "tags": [
  "backend",
  "prometheus",
  "go"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "HTTP Request Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum[1m]) / rate(http_request_duration_seconds_count[1m])",
     "legendFormat": "{{endpoint}} - {{method}}"
    }
   ]
  },
  {
   "title": "DB Query Latency (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(db_query_latency_total_sum[1m]) / rate(db_query_latency_total_count[1m])",
     "legendFormat": "{{operation}}"
    }
   ]
  },
  {
   "title": "Cache Hits & Misses",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "rate(cache_hits_total[1m])", "legendFormat": "Cache Hit - {{cache_key}}" },
    { "expr": "rate(cache_misses_seconds[1m])", "legendFormat": "Cache Miss - {{cache_key}}" }
   ]
  },
  {
   "title": "Cache Hit Ratio",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(cache_hits_total[1m]) / (rate(cache_hits_total[1m]) + rate(cache_misses_seconds[1m]))",
     "legendFormat": "{{cache_key}}"
    }
   ]
  }
 ]
}